name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  continuous-integration:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: cargo install cargo-audit cargo-nextest
      - name: Static Analysis
        run: cargo clippy --all-targets --all-features -- -Dclippy::all
      - name: Test suite
        run: cargo nextest run
      - name: Vulnerability check
        run: cargo audit
      - name: Build executable
        run: cargo build
